# Generated by Django 3.1.3 on 2020-12-15 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('room_number', models.IntegerField()),
                ('phone_number', models.CharField(max_length=11)),
                ('subdivisions', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polis_OMS', models.CharField(max_length=16)),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('passport_data', models.TextField(max_length=255)),
                ('SNILS', models.CharField(max_length=11)),
                ('initial_inspection', models.BooleanField(blank=True)),
                ('date_of_next_meet', models.DateField(null=True)),
                ('work_phone', models.CharField(max_length=11)),
                ('home_phone', models.CharField(blank=True, max_length=11)),
                ('registration_address', models.TextField(max_length=255)),
                ('residence_address', models.TextField(max_length=255)),
                ('e_mail', models.CharField(blank=True, max_length=255)),
                ('sector', models.IntegerField()),
                ('place_of_work', models.TextField(blank=True, max_length=255)),
                ('blood_type', models.IntegerField(blank=True)),
                ('rhesus_factor', models.CharField(blank=True, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('admin_rights', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time_reception', models.IntegerField()),
                ('start_hour', models.IntegerField()),
                ('start_minute', models.IntegerField()),
                ('end_hour', models.IntegerField()),
                ('end_minute', models.IntegerField()),
                ('id_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('reception_start_hour', models.IntegerField()),
                ('reception_start_minute', models.IntegerField()),
                ('reception_end_hour', models.IntegerField()),
                ('reception_end_minute', models.IntegerField()),
                ('status', models.BooleanField()),
                ('patient_polis_OMS', models.CharField(blank=True, max_length=150)),
                ('patient_FIO', models.CharField(blank=True, max_length=16)),
                ('id_Schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.schedule')),
            ],
        ),
    ]
