# Generated by Django 3.1.3 on 2020-12-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='blood_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='rhesus_factor',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
